import type { NextPage } from "next";
import Head from "next/head";
import { useState } from "react";
import { AiOutlineMenu } from "react-icons/ai";
import NavList from "../components/NavList";
import OverLay from "../components/OverLay";
import SideBar from "../components/SideBar";

const Home: NextPage = () => {
  const [isDrawerOpen, setIsDrawerOpen] = useState(false);
  const openDrawer = () => setIsDrawerOpen(true);
  const closeDrawer = () => setIsDrawerOpen(false);

  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      {/* Header */}
      <header className="bg-blue-600">
        <div className=" max-w-6xl mx-auto px-5">
          <div className="h-[150px] flex items-center justify-between">
            <div>
              <h2 className=" text-2xl text-white">Logo</h2>
            </div>
            <div className="hidden md:block">
              <ul className="flex gap-5">
                <NavList linkName="Home" />
                <NavList linkName="Blog" />
                <NavList linkName="Portfolio" />
              </ul>
            </div>
            <div className="md:hidden">
              <AiOutlineMenu
                onClick={openDrawer}
                cursor={"pointer"}
                color="#fff"
                size={25}
              />
            </div>
          </div>
        </div>
      </header>
      {/* Sidebar */}
      <SideBar isDrawerOpen={isDrawerOpen} />
      {/* overlay */}
      <OverLay closeDrawer={closeDrawer} isDrawerOpen={isDrawerOpen} />
    </div>
  );
};

export default Home;
